## This is a compilation of 70 Numpy exercises with solutions from the webpage:

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

#### 1. Import numpy as np and see the version

Import numpy as np and print the version number.

In [14]:
import numpy as np

In [5]:
print(np.__version__)

1.19.2


#### 2. How to create a 1D array?

Create a 1D array of numbers from 0 to 9

 Desired Output
 > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. How to create a boolean array?
Create a 3×3 numpy array of all True’s

In [22]:
# numpy.repeat(a, repeats, axis=None)
# Repeat elements of an array.

bool_array = np.repeat(True,9).reshape(3,3)
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# More examples of repeating elements of an array

>>> np.repeat(3, 4)
array([3, 3, 3, 3])

>>> x = np.array([[1,2],[3,4]])
>>> np.repeat(x, 2)
array([1, 1, 2, 2, 3, 3, 4, 4])  # flatens array by repeating each element twice in this case

>>> np.repeat(x, 3, axis=1)      # repeats along the row; each element thrice
array([[1, 1, 1, 2, 2, 2],       # did not flatten as axis provided for 2d array
       [3, 3, 3, 4, 4, 4]])      

>>> np.repeat(x, [1, 2], axis=0) # repeats [1,2] once and [3,4] twice along axis=0
array([[1, 2],
       [3, 4],
       [3, 4]])

>>> np.repeat(x, [3, 4], axis=0) # repeats [1,2] thrice and [3,4] four times along axis=0
array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [21]:
# Another example of returning boolean array

bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


#### 4. How to extract items that satisfy a given condition from 1D array?

Extract all odd numbers from arr.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


 Desired Output:
 > array([1, 3, 5, 7, 9])

In [30]:
# Create a 1D array
arr = np.arange(10)
print(arr)

# Create a boolean array by applying condition for odd numbers from the array
# Comparison operator will be applied to each element in array 
# and number of elements in returned bool array will be same as original array. 
# But but for every element that satisfies the condition there will be True in array 
# and False for others in the returned array.
bool_arr = (arr%2 != 0)
print(bool_arr)

# Pass this bool array to subscript operator [] of original array to return 
# a new array containing elements from original array for which it was True in bool array
new_arr = arr[bool_arr]
new_arr

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [31]:
# We can do all that in a single line by passing complete comparing expression in [] operator
odd_arr = arr[arr%2 != 0]
odd_arr

array([1, 3, 5, 7, 9])

#### 5. How to replace items that satisfy a condition with another value in numpy array?

Replace all odd numbers in arr with -1.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


 Desired Output:
>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [41]:
arr = np.arange(10)

arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])