## This is a compilation of 70 Numpy exercises with solutions from the webpage:

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

#### 1. Import numpy as np and see the version

Import numpy as np and print the version number.

In [2]:
import numpy as np

In [5]:
print(np.__version__)

1.19.2


#### 2. How to create a 1D array?

Create a 1D array of numbers from 0 to 9

 Desired Output
 > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. How to create a boolean array?
Create a 3×3 numpy array of all True’s

In [22]:
# numpy.repeat(a, repeats, axis=None)
# Repeat elements of an array.

bool_array = np.repeat(True,9).reshape(3,3)
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# More examples of repeating elements of an array

>>> np.repeat(3, 4)
array([3, 3, 3, 3])

>>> x = np.array([[1,2],[3,4]])
>>> np.repeat(x, 2)
array([1, 1, 2, 2, 3, 3, 4, 4])  # flatens array by repeating each element twice in this case

>>> np.repeat(x, 3, axis=1)      # repeats along the row; each element thrice
array([[1, 1, 1, 2, 2, 2],       # did not flatten as axis provided for 2d array
       [3, 3, 3, 4, 4, 4]])      

>>> np.repeat(x, [1, 2], axis=0) # repeats [1,2] once and [3,4] twice along axis=0
array([[1, 2],
       [3, 4],
       [3, 4]])

>>> np.repeat(x, [3, 4], axis=0) # repeats [1,2] thrice and [3,4] four times along axis=0
array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [21]:
# Another example of returning boolean array

bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


#### 4. How to extract items that satisfy a given condition from 1D array?

Extract all odd numbers from arr.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


 Desired Output:
 > array([1, 3, 5, 7, 9])

In [30]:
# Create a 1D array
arr = np.arange(10)
print(arr)

# Create a boolean array by applying condition for odd numbers from the array
# Comparison operator will be applied to each element in array 
# and number of elements in returned bool array will be same as original array. 
# But but for every element that satisfies the condition there will be True in array 
# and False for others in the returned array.
bool_arr = (arr%2 != 0)
print(bool_arr)

# Pass this bool array to subscript operator [] of original array to return 
# a new array containing elements from original array for which it was True in bool array
new_arr = arr[bool_arr]
new_arr

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [31]:
# We can do all that in a single line by passing complete comparing expression in [] operator
odd_arr = arr[arr%2 != 0]
odd_arr

array([1, 3, 5, 7, 9])

#### 5. How to replace items that satisfy a condition with another value in numpy array?

Replace all odd numbers in arr with -1.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


 Desired Output:
>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [41]:
arr = np.arange(10)

arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 6. How to replace items that satisfy a condition without affecting the original array?
Replace all odd numbers in arr with -1 without changing arr.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Desired Output:

out  >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr  >  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# numpy.copy(a, order='K', subok=False)
# Return an array copy of the given object.

arr = np.arange(10)

arr2 = np.copy(arr)
arr2[arr2%2 != 0] = -1
print(f"Modified array: {arr2}")
print(f"Original array: {arr}")

Modified array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original array: [0 1 2 3 4 5 6 7 8 9]


#### 7. How to reshape an array?
Convert a 1D array to a 2D array with 2 rows.

Input:

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Desired Output:
> array([[0, 1, 2, 3, 4],
 >        [5, 6, 7, 8, 9]])

In [14]:
np.arange(10).reshape(2,5)

# or
# np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 8. How to stack two arrays vertically?
Stack arrays a and b vertically.

Input:

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

> array([[0, 1, 2, 3, 4],
>        [5, 6, 7, 8, 9],
>        [1, 1, 1, 1, 1],
>        [1, 1, 1, 1, 1]])

In [29]:
# Method 1 - vstack (given solution)
# numpy.vstack(tup)
# Stack arrays in sequence vertically (row wise).

a = np.arange(10).reshape(2,-1)
print(a)

b = np.repeat(1, 10).reshape(2,-1)
print(b)

np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# Method 2 - concatenate 
# numpy.concatenate((a1, a2, ...), axis=0, out=None)
# Join a sequence of arrays along an existing axis.

a = np.arange(10).reshape(2,-1)
print(a)

b = np.repeat(1, 10).reshape(2,-1)
print(b)

np.concatenate((a,b), axis=0)  # here axis=0 is optional as it's the default axis in the syntax

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# if axis=1, concatenates column-wise
print(np.concatenate((a,b), axis=1))

print()

# if axis=None, flatens array one after the other
print(np.concatenate((a,b), axis=None))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

[0 1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1]


#### 9. How to stack two arrays horizontally?
Stack the arrays a and b horizontally.

Input:

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
 >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
# Method 1 - hstack (given solution)
# numpy.hstack(tup)
# Stack arrays in sequence horizontally (column wise).

a = np.arange(10).reshape(2,-1)
print(a)

b = np.repeat(1, 10).reshape(2,-1)
print(b)

np.hstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
# Method 2 - concatenate

np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### 10. How to generate custom sequences in numpy without hardcoding?
Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [52]:
# numpy.tile(A, reps)
# Construct an array by repeating A the number of times given by reps.

a = np.array([1,2,3])

b = np.repeat(a,3)
c = np.tile(a,3)
np.concatenate((b,c)) #or #np.concatenate((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### 11. How to get the common items between two python numpy arrays? 
Get the common items between a and b.

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

> array([2, 4])

In [65]:
# numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
# Find the unique elements of an array.

# Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:
# the indices of the input array that give the unique values
# the indices of the unique array that reconstruct the input array
# the number of times each unique value comes up in the input array

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

# a[a==b] returns array([2,2,4,4])
np.unique(a[a==b])

array([2, 4])

#### 12. How to remove from one array those items that exist in another?
From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])


Desired Output:
> array([1,2,3,4])

In [69]:
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

a[~np.isin(a,b)] # a[np.isin(a,b)] returns array([5])

# np.isin to find the common elements (returns an array of Booleans). 
# To filter only False, use ~ 

array([1, 2, 3, 4])

#### 13. How to get the positions where elements of two arrays match?
Get the positions where elements of a and b match.

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

> (array([1, 3, 5, 7]),)

In [78]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

#### 14. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:

> (array([6, 9, 10]),)

In [87]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a>5) & (a<=10)]

array([ 6,  9, 10])

#### 15. How to make a python function that handles scalars to work on numpy arrays?

Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    
    """
    Get the maximum of two items
    """
    
    if x >= y:
        return x
    else:
        return y
print("Result of the maxx function")

maxx(1, 5)

Input:

a = np.array([5, 7, 9, 8, 6, 4, 5])

b = np.array([6, 3, 4, 8, 9, 7, 1])

Desired Output:

> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [12]:
def maxx(x, y):
    """
    Get the maximum of two items
    """
    
    if x >= y:
        return x
    else:
        return y
print("Result of the maxx function(scalar):", maxx(1,5))


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def pair_max(a,b):
    
    # using a list comprehension to find the max between 2 arrays elementwise (using zip) 
    # and convert to numpy array
    return np.array([max(x, y) for x, y in zip(a, b)])
    
pair_max(a,b)

Result of the maxx function(scalar): 5


array([6, 7, 9, 8, 9, 7, 5])

#### 16. How to swap two columns in a 2d numpy array?

Swap columns 1 and 2 in the array arr.

Input:

arr = np.arange(9).reshape(3,3)

Desired Output:

> array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [24]:
arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:,0], arr[:,1] = arr[:,1], arr[:,0].copy()
arr

# or
# temp = arr[:,0].copy() # temporary variable
# arr[:,0], arr[:,1] = arr[:,1], temp

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 17. How to swap two rows in a 2d numpy array?

Swap rows 1 and 2 in the array arr.

Input:

arr = np.arange(9).reshape(3,3)

Desired Output:

> array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [25]:
arr = np.arange(9).reshape(3,3)
print(arr)

arr[0,:], arr[1,:] = arr[1,:], arr[0,:].copy()
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 18. How to reverse the rows of a 2D array?

Reverse the rows of a 2D array arr.

Input:

arr = np.arange(9).reshape(3,3)

Desired Output:

> array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 19. How to reverse the columns of a 2D array?

Reverse the columns of a 2D array arr.

Input:

arr = np.arange(9).reshape(3,3)

Desired Output:

> array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

#### 20. How to create a 2D array containing random floats between 5 and 10?

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

Desired Output:

> array([[ 8, 10,  8],
       [ 7,  9, 10],
       [ 8,  7,  5],
       [ 5,  9,  7],
       [10,  8,  9]])

#### 21. How to print only 3 decimal places in python numpy array?

Print or show only 3 decimal places of the numpy array rand_arr.

Desired Output(one of many):

> array([[0.351, 0.737, 0.854],
       [0.286, 0.416, 0.714],
       [0.771, 0.027, 0.465],
       [0.989, 0.925, 0.865],
       [0.035, 0.917, 0.971]])

#### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

Pretty print rand_arr by suppressing the scientific notation (like 1e10).

Desired Output:

> array([[ 0.000543,  0.000278,  0.000425],
>        [ 0.000845,  0.000005,  0.000122],
>        [ 0.000671,  0.000826,  0.000137]])

#### 23. How to limit the number of items printed in output of numpy array?

Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

a = np.arange(15)

Desired Output:

> array([ 0,  1,  2, ..., 12, 13, 14])

#### 24. How to print the full numpy array without truncating?

Print the full numpy array a without truncating.

Input:

a = np.arange(15)

Desired Output:

> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?